### ISSUE TITLE
Symlink installation errors

### ISSUE THREAD

**Issue by patrickheeney** [rstacruz/pnpm#122]
```
$ pnpm install flow-bin@^0.21.0
  flow-bin ^0.21.0                                                  ERROR ✗
  bin-wrapper ^2.0.0                                                2.1.0 ✓
  flow-bin@0.21.0! $ node lib/install.js
  flow-bin@0.21.0! module.js:328
  flow-bin@0.21.0!     throw err;
  flow-bin@0.21.0!     ^
  flow-bin@0.21.0! Error: Cannot find module 'deep-extend'
  flow-bin@0.21.0!     at Function.Module._resolveFilename (module.js:326:15)
  flow-bin@0.21.0!     at Function.Module._load (module.js:277:25)
  flow-bin@0.21.0!     at Module.require (module.js:354:17)
  flow-bin@0.21.0!     at require (internal/module.js:12:17)
  flow-bin@0.21.0!     at Object.<anonymous> (node_modules/.tmp/fa15e04c-5d2b-4e95-afa2-444b958fc769/_/index.js:4:18)
  flow-bin@0.21.0!     at Module._compile (module.js:410:26)
  flow-bin@0.21.0!     at Object.Module._extensions..js (module.js:417:10)
  flow-bin@0.21.0!     at Module.load (module.js:344:32)
  flow-bin@0.21.0!     at Function.Module._load (module.js:301:12)
  flow-bin@0.21.0!     at Module.require (module.js:354:17)

 ! Exit code 1
```

It seems to fail on the npm package `rc` which does have the correct dependency: `"deep-extend": "~0.2.5"`. Checking the folder it doesn't appear like it symlinked that specific dependency. 

Installing it directly: `pnpm install rc` works ok, so something is preventing it from being installed from flow. 

**EDIT**: It seems there is a different underlying cause. I have re-run this install 4 times, each with different errors:

```
 ! ENOENT: no such file or directory, open 'node_modules/.store/utila@0.3.3/_/package.json'

  flow-bin@0.21.0! module.js:328
  flow-bin@0.21.0!     throw err;
  flow-bin@0.21.0!     ^
  flow-bin@0.21.0! Error: Cannot find module 'globule'

  flow-bin@0.21.0! $ node lib/install.js
  phantomjs-prebuilt ^2.1.4                                         ERROR ✗
  phantomjs-prebuilt@2.1.4! Error requesting archive.
  phantomjs-prebuilt@2.1.4! Status: 429
```

My `package.json` for testing:

````
  "dependencies": {
    "body-parser": "^1.15.0",
    "cors": "^2.7.1",
    "debug": "^2.2.0",
    "express": "^4.13.4",
    "express-graphql": "^0.4.9",
    "fs-promise": "^0.4.1",
    "immutable": "^3.7.6",
    "invariant": "^2.2.0",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.4.0",
    "react-router": "^2.0.0",
    "react-router-redux": "^4.0.0-beta",
    "recompose": "^0.15.0",
    "redux": "^3.3.1",
    "redux-thunk": "^1.0.3",
    "swig": "^1.4.2",
    "yargs": "^3.32.0"
  },
  "devDependencies": {
    "babel-cli": "^6.5.1",
    "babel-core": "^6.5.2",
    "babel-eslint": "^5.0.0-beta8",
    "babel-loader": "^6.2.2",
    "babel-plugin-transform-runtime": "^6.5.2",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.5.2",
    "babel-runtime": "^6.5.0",
    "better-npm-run": "0.0.7",
    "chai": "^3.5.0",
    "chai-as-promised": "^5.2.0",
    "chai-enzyme": "^0.4.0",
    "cheerio": "^0.20.0",
    "codecov": "^1.0.1",
    "connect-history-api-fallback": "^1.1.0",
    "css-loader": "^0.23.1",
    "cssnano": "^3.5.1",
    "enzyme": "^1.5.0",
    "eslint": "^2.0.0",
    "eslint-config-standard": "^5.1.0",
    "eslint-config-standard-react": "^2.2.0",
    "eslint-plugin-babel": "^3.1.0",
    "eslint-plugin-flow-vars": "^0.1.3",
    "eslint-plugin-react": "^3.16.1",
    "eslint-plugin-standard": "^1.3.2",
    "expect": "^1.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "flow-bin": "^0.21.0",
    "flow-interfaces": "^0.2.1",
    "fs-extra": "^0.26.5",
    "html-webpack-plugin": "^2.8.1",
    "imports-loader": "^0.6.5",
    "isparta": "4.0.0",
    "isparta-loader": "^2.0.0",
    "istanbul": "^0.4.2",
    "json-loader": "^0.5.4",
    "karma": "^0.13.20",
    "karma-coverage": "^0.5.3",
    "karma-mocha": "^0.2.1",
    "karma-mocha-reporter": "^1.1.5",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.4.5",
    "node-sass": "^3.4.2",
    "nodemon": "^1.8.1",
    "phantomjs-polyfill": "0.0.1",
    "phantomjs-prebuilt": "^2.1.4",
    "postcss-loader": "^0.8.0",
    "react-addons-test-utils": "^0.14.7",
    "rimraf": "^2.5.1",
    "sass-loader": "^3.1.2",
    "sinon": "^1.17.3",
    "sinon-chai": "^2.8.0",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "1.12.13",
    "webpack-dev-middleware": "^1.5.1",
    "webpack-hot-middleware": "^2.7.1"
  }
```

**Comment by patrickheeney** [comment]
I don't know if this is related to the first one, but this is a different app and some errors:

```
 ! ENOENT: no such file or directory, open 'node_modules/.store/lodash.tostring@4.1.1/_/package.json'

 ! ENOENT: no such file or directory, open 'node_modules/.store/is-callable@1.1.2/_/package.json'
```

With the following:

```
  "dependencies": {},
  "devDependencies": {
    "babel-cli": "^6.5.1",
    "babel-core": "^6.5.2",
    "babel-eslint": "^5.0.0-beta8",
    "babel-plugin-transform-runtime": "^6.5.2",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.5.2",
    "babel-runtime": "^6.5.0",
    "eslint": "^2.0.0",
    "eslint-config-standard": "^5.1.0",
    "expect": "^1.14.0",
    "fs-promise": "^0.4.1",
    "glob": "^7.0.0",
    "graceful-fs": "^4.1.3",
    "isparta": "4.0.0",
    "istanbul": "^0.4.2",
    "mocha": "^2.4.5",
    "npm-registry-client": "^7.0.9",
    "pnpm": "^0.18.0",
    "rimraf": "^2.5.1",
    "semver": "^5.1.0",
    "shelljs": "^0.6.0",
    "yargs": "^3.32.0"
  },
```

**Comment by iamstarkov** [comment]
tried just now to install `pnpm install flow-bin` and have no errors. can you try again?
if it still fails, can you provide nodejs and pnpm versions?

**Comment by patrickheeney** [comment]
I still have the same problem(s), but `flow-bin` didn't error for me. Try the first `package.json` I supplied in the original post and it is very likely to fail on one of the dependencies. 

```
$ npm -v
2.14.12

$ node -v
v4.2.6
```

Installed it via `nvm` on `osx 10.11.3`.

**Comment by iamstarkov** [comment]
some package which are failing often:
* `lodash._reinterpolate`@3.0.0
* `is-primitive`@2.0.0

**Comment by misterbyrne** [comment]
Possibly related to #78

**Comment by rstacruz** [comment]
This might be a little different than #78. 

```
  flow-bin@0.21.0! $ node lib/install.js
  flow-bin@0.21.0! module.js:328
  flow-bin@0.21.0!     throw err;
  flow-bin@0.21.0!     ^
  flow-bin@0.21.0! Error: Cannot find module 'deep-extend'
```

This seems to be a case where `flow-bin` was attempted to be built (`npm run postinstall`), but it's dependencies aren't ready yet.

**Comment by zkochan** [comment]
@patrickheeney is it reproducible as of pnpm v0.26.1?

There were a lot of bug fixes since you posted this issue and I cannot reproduce it currently.

**Comment by patrickheeney** [comment]
@zkochan Working for me on `v0.26.1`. Will close this and re-open if I run into it again. Nice work!
