### ISSUE TITLE
Fails on windows

### ISSUE THREAD

**Issue by BryanCrotaz** [rstacruz/pnpm#291]
```
Error: ENOENT: no such file or directory, unlink 'C:\projects\ember-dds\node_modules\.tmp\528cd0bb-5dee-4c84-a00f-eabbda3b793a\_\node_modules\.bin\semver'
    at Error (native)
```
Seeing this on multiple packages.

Installed using 
```
npm install -g pnpm
npm cache clear
rmdir /s/q node_modules
pnpm install
```

Running as administrator with symlink permissions

**Comment by BryanCrotaz** [comment]
callstack:
```
Error: ENOENT: no such file or directory, symlink 'C:\projects\ember-dds\node_modules\.tmp\b29ed689-6a38-46f7-8d2d-c8aed1c19253\_\node_modules\npm\bin\npm-cli.js' -> 'C:\projects\ember-dds\node_modules\.tmp\b29ed689-6a38-46f7-8d2d-c8aed1c19253\_\node_modules\.bin\npm'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at forceSymlink (C:\npm\global\node_modules\pnpm\lib\fs\force_symlink.js:17:8)
    at C:\npm\global\node_modules\pnpm\lib\fs\force_symlink.js:27:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by BryanCrotaz** [comment]
Also seeing this error on a minority of the failed packages:

```
Error: EBUSY: resource busy or locked, unlink 'C:\projects\ember-dds\node_modules\.tmp\1e078abd-86e9-439d-990e-baea8d0c22a4\_\node_modules\.bin\nopt'
    at Error (native)
```

**Comment by zkochan** [comment]
What pnpm version do you use?

Could you try the unreleased one? I added improved Windows support. For instance, no need to run in it with admin permissions anymore. Install it via `npm i -g rstacruz/pnpm`

**Comment by BryanCrotaz** [comment]
Better - this error is gone but it still fails

**Comment by zkochan** [comment]
Can you post the set of your dependencies here, so that I can reproduce it on my PC?

**Comment by BryanCrotaz** [comment]
See issue #292
