### ISSUE TITLE
EACCESS error on runas

### ISSUE THREAD

**Issue by cprecioso** [rstacruz/pnpm#344]
### pnpm version:
0.29.1

### Code to reproduce the issue:
`pnpm i runas`

### Expected behavior:
It installs

### Actual behavior:
```sh
$ pnpm i runas
  runas                                                             ERROR ✗    
  nan 2.x                                                           2.4.0 ✓ 

 ! spawn EACCES

$ pnpm i --debug runas

 ! spawn EACCES
```
(`npm` installs it just fine, so it must be `pnpm`)

### Additional information:

 - `node -v` prints: v6.5.0
 - Windows, OS X, or Linux?: OS X 10.11.6

**Comment by zkochan** [comment]
Works on Linux

Could you please set the env variable DEBUG_PROMISE to true, run again and post the output?

**Comment by cprecioso** [comment]
Here you go:

```sh
$ export DEBUG_PROMISE=true
$ pnpm i runas             
  runas                                                             ERROR ✗    
  nan 2.x                                                           2.4.0 ✓ 

 ! spawn EACCES
Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at spawn (/Users/carlos/.nvm/versions/node/v6.5.0/lib/node_modules/pnpm/node_modules/cross-spawn/index.js:17:18)
    at Promise (/Users/carlos/.nvm/versions/node/v6.5.0/lib/node_modules/pnpm/lib/run_script.js:15:18)
    at runScript (/Users/carlos/.nvm/versions/node/v6.5.0/lib/node_modules/pnpm/lib/run_script.js:14:10)
    at fs.stat.then._ (/Users/carlos/.nvm/versions/node/v6.5.0/lib/node_modules/pnpm/lib/install/post_install.js:34:14)
```

**Comment by zkochan** [comment]
What does this return? `npm get unsafe-perm`

**Comment by cprecioso** [comment]
`true`

**Comment by zkochan** [comment]
hey @cprecioso, I published a change to v0.31.0 that I think might fix your error.

Please update your pnpm and try again. If it won't work create a gist from your `pnpm-debug.log` and post the ling here. (`pnpm-debug.log` generation was also added in v0.31.0)

**Comment by cprecioso** [comment]
https://gist.githubusercontent.com/cprecioso/e08806857465c2ef860458edff123763/raw/d38ba5a105ed5ffed7df9e3b9f55678eff7b66d6/pnpn-debug.yml

**Comment by iamstarkov** [comment]
seems like permissions related problem

**Comment by iamstarkov** [comment]
can verify it https://gist.github.com/iamstarkov/9ec39a9bdf66d5bc20bb55e29f580f87

**Comment by iamstarkov** [comment]
and this is strange, because i didnt have permissions problems neither with npm, nor with pnpm for years

**Comment by iamstarkov** [comment]
```
➜  mapbox-gl-js git:(master) DEBUG_PROMISE=true pnpm i runas
  runas                                                             3.1.1 ✓    
  nan 2.x                                                           2.4.0 ✓    

 ! spawn EACCES
Error: spawn EACCES
    at exports._errnoException (util.js:1012:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:372:9)
    at spawn (/usr/local/lib/node_modules/pnpm/node_modules/cross-spawn/index.js:17:18)
    at Promise (/usr/local/lib/node_modules/pnpm/lib/run_script.js:15:18)
    at runScript (/usr/local/lib/node_modules/pnpm/lib/run_script.js:14:10)
    at fs.stat.then._ (/usr/local/lib/node_modules/pnpm/lib/install/post_install.js:35:14)
```

**Comment by zkochan** [comment]
maybe because cross-spawn is used instead of child_process. This was a change made maybe 1 or 2 month ago

**Comment by iamstarkov** [comment]
also the reason behind not reproducing on linux can be in runas's nan's bindings https://github.com/atom/node-runas/blob/master/binding.gyp

**Comment by iamstarkov** [comment]
but i dont have any experience with nan or bindings(

**Comment by zkochan** [comment]
@cprecioso I published  a possible fix to `@zkochan/pnpm`

please try if it fixes the issue

**Comment by zkochan** [comment]
@cprecioso could you please retry with the latest pnpm

if it still fails check what will this return `npm get node-gyp`

**Comment by cprecioso** [comment]
Yep, it works. Going to close the issue then. Thanks!
