### ISSUE TITLE
Issue with babel & babel-plugin-lodash

### ISSUE THREAD

**Issue by julien-f** [rstacruz/pnpm#393]
### Code to reproduce the issue:

https://github.com/julien-f/issue-babel-lodash-pnpm

### Expected behavior:

`pnpm i` should work fine.

### Actual behavior:

Packages installation works fine but the build fails:

```
> @ build issue-babel-lodash-pnpm
> NODE_ENV=production babel --out-dir=dist/ src/

Error: src/index.js: Cannot find module
    at PluginPass.Program (issue-babel-lodash-pnpm/node_modules/babel-plugin-lodash/lib/index.js:97:15)
    at newFn (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (issue-babel-lodash-pnpm/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:79:12)
```

### Additional information:

 - `node -v` prints: v6.4.0
 - Windows, OS X, or Linux?: Linux

/cc @jdalton

**Comment by jdalton** [comment]
It looks like you're missing `lodash` as a dependency.

**Comment by julien-f** [comment]
@jdalton You're right! Shame on me :p

**Comment by julien-f** [comment]
@jdalton I understand this is a bit weird but shouldn't it work anyway if `lodash` is not used?

I like to have `babel-plugin-lodash` set up in all my projects without installing `lodash` by default.

**Comment by jdalton** [comment]
It won't work without it because it generates resolves paths against the `lodash` you're using.

**Comment by julien-f** [comment]
Makes sense, too bad for my template module ^^
