### ISSUE TITLE
Cannot find module 'reflect-metadata'

### ISSUE THREAD

**Issue by aecz** [rstacruz/pnpm#418]
pnpm 0.40.0

### Code to reproduce the issue:
```
pnpm i -g angular-cli
ng -v
```

### Expected behavior:
Version of angular-cli should be displayed.

### Actual behavior:
```
Cannot find module 'reflect-metadata'
Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\@ngtools\webpack\src\index.js:5:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aecz\.pnpm\node_modules\angular-cli\models\webpack-build-typescript.js:5:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aecz\.pnpm\node_modules\angular-cli\models\webpack-config.js:2:34)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aecz\.pnpm\node_modules\angular-cli\tasks\build-webpack.js:6:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aecz\.pnpm\node_modules\angular-cli\commands\build.js:3:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (C:\Users\aecz\.pnpm\node_modules\angular-cli\addon\index.js:21:16)
    at C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:391:15)
    at Project.eachAddonCommand (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:426:30)
    at module.exports (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\lib\cli\cli.js:34:26)
    at tryCatch (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\Users\aecz\.pnpm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Additional information:
node 6.5.0
Windows 7

**Comment by iamstarkov** [comment]
@aecz can you help me to find dependency chain from `angular-cli` to `reflect-metadata`? because `angular-cli` doesnt depend on this package directly and `angular-cli\node_modules\@ngtools\webpack\src\index.js` kind of obscure to deal with

**Comment by aecz** [comment]
Not sure what you are asking for ;)
`reflect-metadata `is a dependency of `@angular/compiler-cli` and in `.pnpm/node_modules/.store/node_modules`, there is the link to `reflect-metadata` so `@ngtools/webpack` should find it but dont :(

This is related to this PR https://github.com/rstacruz/pnpm/pull/46 that is supposed to solve this kind of issues.
Hope that helps.

**Comment by Akkuma** [comment]
I'm seeing pretty much the same issue as well, but for different dependencies.

**Comment by zkochan** [comment]
Track this issue https://github.com/rstacruz/pnpm/issues/403

I am finishing the pull request so the fix will be ready soon

**Comment by zkochan** [comment]
This has to work now with the `--flat-tree` option. The feature is for now published under the `next` dist-tag

**Comment by aecz** [comment]
I have a different error now:
```
npm i -g pnpm@next (0.42.4)
pnpm i -g angular-cli@1.0.0-beta.17 --flat-tree
ng -v
```
Installation fails with issue:
```
Flattening the dependency tree
 ! ENOENT: no such file or directory, stat 'C:\Users\aecz\.pnpm\node_modules\handle-thing'
```
Link exists for destination folder not:
```
24/10/2016  13:16    <JUNCTION>     handle-thing [C:\Users\aecz\.pnpm\.store\flat\handle-thing@1.2.5\_]
```
I have uninstalled angular-cli, cleared cache but same issue.

**Comment by zkochan** [comment]
@aecz sorry that we've forgotten to reply you. Seems like this issue is gone with latest pnpm/angular. If no and you'd be still interested in pnpm, please create a new issue and we'll investigate.
