### ISSUE TITLE
Intermittent ENOENT errors during symlinking

### ISSUE THREAD

**Issue by misterbyrne** [rstacruz/pnpm#78]
I'm getting a lot of this type of error since getting the latest version...
It looks like a timing thing because it doesn't happen consistently - i.e. not always and when it does with different packages. Always a similar stack trace though.

```
 ! ENOENT: no such file or directory, open 'my-app/node_modules/.store/ansi-styles@2.1.0/_/package.json'
Error: ENOENT: no such file or directory, open '/my-app/node_modules/.store/ansi-styles@2.1.0/_/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at requireJson (/src/pnpm/lib/fs/require_json.js:10:42)
    at symlinkToModules (/src/pnpm/lib/install.js:274:17)
    at /src/pnpm/lib/install.js:97:20
From previous event:
    at /src/pnpm/lib/install.js:97:10
From previous event:
    at install (/src/pnpm/lib/install.js:89:6)
    at /src/pnpm/lib/install_multiple.js:14:12
    at Array.map (native)
    at installMultiple (/src/pnpm/lib/install_multiple.js:13:27)
    at /src/pnpm/lib/install.js:222:16
From previous event:
    at buildInStore (/src/pnpm/lib/install.js:222:6)
    at /src/pnpm/lib/install.js:179:20
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by rstacruz** [comment]
thanks for the detailed stacktrace!

**Comment by rstacruz** [comment]
i'm guessing this is the problem:

```js
/* fetch.js */
// `stream` is a tarball coming from http://registry.npmjs.org/

    stream
      .on('response', start)
      .on('data', _ => { actualShasum.update(_) })
      .on('error', reject)
      .pipe(gunzip()).on('error', reject)
      .pipe(tar.extract(dir, { strip: 1 })).on('error', reject)
      .on('finish', finish)
```

Notice the `on('finish')` — it's waiting for the end of the HTTP stream data, not the end of extracting (which can happen asynchronously).

anyway, just a hypothesis

**Comment by srgpqt** [comment]
Running into this issue *a lot*

**Comment by rstacruz** [comment]
if anyone can help debug, that'd be appreciated! still can't pinpoint exactly what's çausing this.

**Comment by stefanpenner** [comment]
I may have some time sunday, if I remember I'll give it a whirl since ember-cli somewhat consistently has this problem. I would also recommend giving that repo a try \w pnpm, as  it may serve as a good reproduction as it seems to hapen often

**Comment by misterbyrne** [comment]
I haven't had a chance to look at this until today. I did try using the `finish` event on the `tar.extract` stream instead - and the problem still happened. I tried adding a load of logging by monkey patching the `emit` function on file streams in `tar-fs`, the http response stream and instrumenting `pnpm` a bit more, e.g.

```JavaScript
function logEmits(emitter, name) {
  var oldEmit = emitter.emit;
  var debug = require('debug')('emit')
  emitter.emit = function() {
    debug('%s %o', name, arguments[0])
    oldEmit.apply(emitter, arguments);
  }
  return emitter;
}
```

...and then managed to get it to fail (using a high concurrency value). grep for the interesting events...

```
  pnpm:install installing parseurl@~1.3.1 +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'pipe' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/package.json 'pipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/package.json 'open' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/package.json 'prefinish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/package.json 'finish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/package.json 'unpipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/package.json 'close' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/README.md 'pipe' +1ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/README.md 'open' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/README.md 'prefinish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/README.md 'finish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/README.md 'unpipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/README.md 'close' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/LICENSE 'pipe' +8ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/LICENSE 'open' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/LICENSE 'prefinish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/LICENSE 'finish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/LICENSE 'unpipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/LICENSE 'close' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/index.js 'pipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/index.js 'open' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/index.js 'prefinish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/index.js 'finish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/index.js 'unpipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/index.js 'close' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'entry' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/HISTORY.md 'pipe' +1ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/HISTORY.md 'open' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/HISTORY.md 'prefinish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/HISTORY.md 'finish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/HISTORY.md 'unpipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_/HISTORY.md 'close' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'prefinish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'prefinish' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'finish' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'finish' +0ms
  emit http://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz 'unpipe' +0ms
  emit /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002/_ 'unpipe' +0ms
  pnpm:install symlinkSelf parseurl +0ms
  pnpm:install installing parseurl@~1.3.1 +0ms
  pnpm:install /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002 => /Users/adam/src/blog/node_modules/.store/parseurl@1.3.1 +1ms
  pnpm:install /Users/adam/src/blog/node_modules/.tmp/c4d53b58-6565-4451-b3d0-b75994670002 => /Users/adam/src/blog/node_modules/.store/parseurl@1.3.1 DONE +0ms
 ! ENOENT: no such file or directory, open '/Users/adam/src/blog/node_modules/.store/parseurl@1.3.1/_/package.json'
```

observations: it seems to be packages with few files that are failing (i.e. not much time passes between extracting `package.json`, doing the rename, and the read that fails)

From what I can tell all the async fs stuff is wired up cirre
